name: Keywords

on:
  workflow_call:
  workflow_dispatch:

env:
  ARTIFACT_NAME: results-keywords-csv
  PROJECT_NAME: charles_stanley

jobs:
  worker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Cleanup CSV
        run: rm -rf csv/*_keyword.csv
      
      - name: Scrape URLs Chunk
        run: python main.py --id ${{ matrix.chunk }} --max 10 --keyword

      - name: Upload MF Partial Data
        uses: actions/upload-artifact@v6
        with:
          name: ${{env.ARTIFACT_NAME}}-${{ matrix.chunk }}
          path: csv/${{env.PROJECT_NAME}}_${{ matrix.chunk }}_keyword.csv
          if-no-files-found: error

  merge-results:
    needs: worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Download All Artifacts
        uses: actions/download-artifact@v6
        with:
          path: csv
          pattern: ${{env.ARTIFACT_NAME}}-*
          merge-multiple: true

      - name: Merge and Commit
        run: python main.py --merge

      - name: Upload Spreadsheet
        uses: actions/upload-artifact@v6
        with:
          name: ${{env.PROJECT_NAME}}
          path: spreadsheet
          if-no-files-found: error

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Updated: Merge CSV Funds results"
 