name: URLs

on:
  workflow_call:
  workflow_dispatch:

env:
  ARTIFACT_NAME: results-urls-csv
  PROJECT_NAME: charles_stanley

jobs:
  worker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
        #chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Cleanup CSV
        run: rm -rf csv/*_url.csv
      
      - name: Scrape URLs Chunk
        run: python main.py --id ${{ matrix.chunk }} --url --max 10

      - name: Upload MF Partial Data
        uses: actions/upload-artifact@v6
        with:
          name: ${{env.ARTIFACT_NAME}}-${{ matrix.chunk }}
          path: csv/${{env.PROJECT_NAME}}_${{ matrix.chunk }}_url.csv
          if-no-files-found: error

  merge-results:
    needs: worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Download All Artifacts
        uses: actions/download-artifact@v6
        with:
          path: csv
          pattern: ${{env.ARTIFACT_NAME}}-*
          merge-multiple: true

      - name: Merge and Commit
        run: python main.py --merge --url

      - name: Upload Spreadsheet
        uses: actions/upload-artifact@v6
        with:
          name: ${{env.PROJECT_NAME}}
          path: spreadsheet
          if-no-files-found: error

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Updated: Merge CSV Funds results"
 